/* Generated By:JJTree: Do not edit this line. ASTAFB.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.openrdf.query.parser.bdpl.ast;

public
class ASTAFB extends SimpleNode {
	private String operator;
	  
	  public void setOperator(String s){
		  operator = s;
	  }
	  
	  public String getOperator(){
		  return operator;
	  }
	  
  public ASTAFB(int id) {
    super(id);
  }

  public ASTAFB(SyntaxTreeBuilder p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data) throws VisitorException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0c128f24e8e5f27c64da35fdcb8b6529 (do not edit this line) */
