/* Generated By:JJTree: Do not edit this line. ASTAFA.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.openrdf.query.parser.bdpl.ast;

public
class ASTAFA extends SimpleNode implements IArrayFilterExpressionOperatorNode{
	 private String operator;
	  
	 @Override
	  public void setOperator(String o){
		  operator = o;
	  }
	  
	 @Override
	  public String getOperator(){
		  return operator;
	  }
	  
  public ASTAFA(int id) {
    super(id);
  }

  public ASTAFA(SyntaxTreeBuilder p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data) throws VisitorException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=65dc1134295595d09e02c84382527c3a (do not edit this line) */
