/* Generated By:JJTree: Do not edit this line. ASTArrayFilterExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.openrdf.query.parser.bdpl.ast;

public
class ASTArrayFilterExpression extends SimpleNode implements IArrayFilterExpressionOperatorNode{
  private String operator;
  
  @Override
  public void setOperator(String o){
	  operator = o;
  }
  
  @Override
  public String getOperator(){
	  return operator;
  }
  
  public ASTArrayFilterExpression(int id) {
    super(id);
  }

  public ASTArrayFilterExpression(SyntaxTreeBuilder p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data) throws VisitorException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d67a7f9b1b266f3d26ddbd81ab1ec37d (do not edit this line) */
