/* Generated By:JJTree: Do not edit this line. ASTArrayFilter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.openrdf.query.parser.bdpl.ast;

public
class ASTArrayFilter extends SimpleNode {
	
	private Object filter;
	
	public void setFilterOjbect(Object o){
		filter = o;
	}
	
	public Object getFilterObject(){
		return filter;
	}
	
  public ASTArrayFilter(int id) {
    super(id);
  }

  public ASTArrayFilter(SyntaxTreeBuilder p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data) throws VisitorException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=00371b74dfb3273d035c75c7d488758f (do not edit this line) */
