/* Generated By:JJTree: Do not edit this line. ASTArrayDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.openrdf.query.parser.bdpl.ast;

public
class ASTArrayDecl extends SimpleNode {
	
  private String size;
  
  public String getSize() {
	return size;
  }

  public void setSize(String size) {
	this.size = size;
  }

  public ASTArrayDecl(int id) {
    super(id);
  }

  public ASTArrayDecl(SyntaxTreeBuilder p, int id) {
    super(p, id);
  }



  /** Accept the visitor. **/
  public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data) throws VisitorException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5508de2558170f906930221cfc61b9ff (do not edit this line) */
