/* Generated By:JJTree: Do not edit this line. ASTDynamicArrayDef1.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.openrdf.query.parser.bdpl.ast;

public
class ASTDynamicArrayDef1 extends SimpleNode implements IArrayDecl{
  
  private String source;	
  private boolean checked = false;
  
  public ASTDynamicArrayDef1(int id) {
    super(id);
  }

  public ASTDynamicArrayDef1(SyntaxTreeBuilder p, int id) {
    super(p, id);
  }
  
  public String getSource(){
	  return source;
  }
  
  public void setSource(String s){
	  source = s;
  }
  
  public void setChecked(boolean b){
	  checked = b;
  }
  
  public boolean getChecked(){
	  return checked;
  }
  
  /** Accept the visitor. **/
  public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data) throws VisitorException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b9196b89f2a1f8633764a5bb5627d83b (do not edit this line) */