/* Generated By:JJTree: Do not edit this line. ASTStaticArrayDef1.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.openrdf.query.parser.bdpl.ast;

public
class ASTStaticArrayDef1 extends SimpleNode implements ArrayDef{
	private String source;	
	
  public ASTStaticArrayDef1(int id) {
    super(id);
  }

  public ASTStaticArrayDef1(SyntaxTreeBuilder p, int id) {
    super(p, id);
  }
  
  public String getSource(){
	  return source;
  }
  
  public void setSource(String s){
	  source = s;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data) throws VisitorException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4a8beab39687d521cc1676e48016e29e (do not edit this line) */