#!/bin/bash

### BEGIN INIT INFO
# Provides:             dcep
# Required-Start:       $syslog
# Required-Stop:        $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Start PLAY Distributed Complex Event Processing (DCEP)
# Description:          Start PLAY Distributed Complex Event Processing (DCEP)
###

NAME="dcep"
DESC="DCEP ${project.version}"

JSVC_EXECUTABLE="$( which jsvc )"
JSVC_PID_FILE=/var/run/dcep.pid

if [ -z "$JSVC_USER" ]; then
	JSVC_USER="$USER"
fi

DIST_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../" && pwd )"
LIB_DIR="$DIST_DIR/lib"
LOG_DIR="$DIST_DIR/log"
CONF_DIR="$DIST_DIR/conf"

JAVA_EXEC="$( which java )"
JAVA_CLASSPATH="$CONF_DIR:$LIB_DIR/${project.build.finalName}.${project.packaging}"
JAVA_MAIN_CLASS="eu.play_project.dcep.distribution.Main"
JAVA_OPTS="-Ddistribution.dir=$DIST_DIR -Djava.security.policy=conf/proactive.java.policy -Dproactive.communication.protocol=pnp -Dproactive.pnp.port=9250 -Dproactive.http.port=9251"

if [ -z "$JAVA_HOME" ]; then
	export JAVA_HOME="$( $JAVA_EXEC -cp "$JAVA_CLASSPATH" -server \
		eu.play_project.dcep.distribution.GetProperty java.home )"
fi

cd $DIST_DIR
mkdir $LOG_DIR

running()
{
# Check if the process is running looking at /proc
# (works for all users)

    # No pidfile, probably no daemon present
    [ ! -f "$JSVC_PID_FILE" ] && return 1

    return 0
}



case "$1" in
  start)
        echo -n "Starting $DESC: "

		$JSVC_EXECUTABLE -cp "$JAVA_CLASSPATH" -user "$JSVC_USER" \
			-pidfile $JSVC_PID_FILE -outfile '&2' -errfile ${LOG_DIR}/${NAME}.log \
			$JAVA_OPTS $JAVA_MAIN_CLASS

        if running ; then
            echo "."
        else
            echo "ERROR."
        fi
        ;;
  stop)
        echo -n "Stopping $DESC: "

		$JSVC_EXECUTABLE -stop -cp "$JAVA_CLASSPATH" -user "$JSVC_USER" \
			-pidfile $JSVC_PID_FILE -outfile '&2' -errfile ${LOG_DIR}/${NAME}.log \ 
			$JAVA_OPTS $JAVA_MAIN_CLASS

        if running ; then
            kill $VIRT_PID
        fi
        echo "$NAME."
        ;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|status}" >&2
        exit 1
        ;;
esac

exit 0
        