#!/bin/bash
toolpath=/opt/dcep
hosts=(141.52.218.16 141.52.218.17 141.52.218.19 141.52.218.20 141.52.219.180 141.52.219.181 141.52.219.183 141.52.219.185 141.52.219.186 141.52.219.188 141.52.219.190 141.52.219.191 141.52.219.192 141.52.219.193 141.52.219.195 141.52.219.196 141.52.219.197 141.52.219.200) 
ssh_usr=root
dcepHttpSource=http://www.home.hs-karlsruhe.de/~obst1011/fzi/play/dcep.zip
dcepJarHttpSource=http://www.home.hs-karlsruhe.de/~obst1011/fzi/play/dcep-jar-with-dependencies.jar

installDcep() {
	for i in "${hosts[@]}"
        do
		ssh -oStrictHostKeyChecking=no $ssh_usr@$i "
			  cd /opt/ && 
			  rm -fr dcep ; 
			  rm dcep.zip ; 
			  wget -nc -nv $dcepHttpSource &&
			  unzip -o dcep.zip &&
			  chmod u+x ./dcep/bin/* &&
			  cat ./dcep/bin/exportPrologPath >> ~/.bashrc" &
	done
}

updateJarFile() {
	for i in "${hosts[@]}"
	do
		ssh -oStrictHostKeyChecking=no $ssh_usr@$i "cd $toolpath && 
			   rm ./lib/dcep-jar-with-dependencies.jar ;
			   wget -nv $dcepJarHttpSource -P ./lib/" &
	done
}

runTest() {
      	ssh -oStrictHostKeyChecking=no $ssh_usr@${hosts[0]} "cd $toolpath && ./bin/dEtalis restart" &
	ssh -oStrictHostKeyChecking=no $ssh_usr@${hosts[3]} "cd $toolpath && ./bin/dEtalis restart" & 
      	sleep 5 
	ssh -oStrictHostKeyChecking=no $ssh_usr@${hosts[1]}  "cd $toolpath && ./bin/subscriber restart ${hosts[0]}" &
	ssh -oStrictHostKeyChecking=no $ssh_usr@${hosts[4]}  "cd $toolpath && ./bin/subscriber restart ${hosts[3]}" &	

	ssh -oStrictHostKeyChecking=no $ssh_usr@${hosts[11]} "cd $toolpath && ./bin/publisher  restart registerPatterns    ${hosts[3]} ${hosts[0]}" &
	ssh -oStrictHostKeyChecking=no $ssh_usr@${hosts[2]}  "cd $toolpath && ./bin/publisher  restart registerPatternsNot ${hosts[3]} ${hosts[0]}" &
}

getLogs() {
        for i in "${hosts[@]}"
        do
                scp -oStrictHostKeyChecking=no $ssh_usr@$i:$toolpath/log/dcep.log ./dcep-$i-${1}.log
        done
}

clearLogs() {
        for i in "${hosts[@]}"
        do
		ssh -oStrictHostKeyChecking=no $ssh_usr@$i "rm $toolpath/log/dcep.log" &
        done
}


prepareNewHost() {
	ssh -oStrictHostKeyChecking=no $ssh_usr@${1} "
		wget -nv https://raw.github.com/play-project/play-dcep/master/play-dcep-distribution/src/main/scripts/software.sh &&
		chmod u+x software.sh &&
		./software.sh cep-engine" &
}

prepareAllHosts() {
        for i in "${hosts[@]}"
        do
		ssh -oStrictHostKeyChecking=no $ssh_usr@$i "
                	rm software.sh ;
			wget -nc -nv https://raw.github.com/play-project/play-dcep/856f576ffab6110adaaceabb3ffd46507605afe5/play-dcep-distribution/src/main/scripts/software.sh &&
                	chmod u+x software.sh &&
                	./software.sh cep-engine" &
	done
}

updateTime() {
        for i in "${hosts[@]}"
        do
                ssh -oStrictHostKeyChecking=no $ssh_usr@$i "ntpdate 0.de.pool.ntp.org 1.de.pool.ntp.org 2.de.pool.ntp.org" & 
        done
}

updateHostConfig() {

	for i in "${hosts[@]}"
        do
            ssh -oStrictHostKeyChecking=no $ssh_usr@$i "echo  $i.dcep.play-project.eu > /etc/hostname"& 
            ssh -oStrictHostKeyChecking=no $ssh_usr@$i "/etc/init.d/hostname.sh"&
	    for j in "${hosts[@]}"
            do
		ssh -oStrictHostKeyChecking=no $ssh_usr@$j "echo $i $i.dcep.play-project.eu >>  /etc/hosts" &
            done

        done

}

case "$1" in
	runTest)
		updateTime
		runTest
	;;

	installDcep)
		installDcep
	;;

	updateJarFile)
		updateJarFile
	;;

	prepareAllHosts)
		prepareAllHosts
	;;

	prepareNewHost)
		prepareNewHost "$2"
	;;
	getLogs)
		getLogs "$2"
	;;
	clearLogs)
                clearLogs 
        ;;

	updateHostConfig)
		updateHostConfig
	;;
 

 	*)
		echo "Configure DCEP-Node: {installDcep|updateJarFile|runTest}"
		exit 1
  	;;
esac

exit 0

